import { SensorReading } from '../domain/models/SensorReading.js';
import { SensorReadingRepository } from '../repositories/SensorReadingRepository.js';
import { AIEvaluationRepository } from '../repositories/AIEvaluationRepository.js';
import { AlertRepository } from '../repositories/AlertRepository.js';
import { DeviceRepository } from '../repositories/DeviceRepository.js';
import { WaterQualityAI } from '../ai-engine/WaterQualityAI.js';
import { config } from '../config/index.js';
import { logger } from '../config/logger.js';

/**
 * Service: Sensor Ingestion
 * Handles real-time sensor data ingestion and AI processing
 */
export class SensorIngestionService {
  constructor() {
    this.sensorReadingRepo = new SensorReadingRepository();
    this.aiEvaluationRepo = new AIEvaluationRepository();
    this.alertRepo = new AlertRepository();
    this.deviceRepo = new DeviceRepository();
    this.aiEngine = new WaterQualityAI({
      debounceMs: config.ai.debounceMs,
      rollingWindowSize: config.ai.rollingWindowSize,
      trendDetectionSamples: config.ai.trendDetectionSamples,
    });
  }

  /**
   * Process incoming sensor reading
   * This is the main entry point for sensor data
   */
  async ingestReading(rawData, deviceId) {
    try {
      // Validate and create domain model
      const reading = new SensorReading({
        deviceId,
        timestamp: rawData.timestamp ? new Date(rawData.timestamp) : new Date(),
        pH: rawData.pH,
        tds: rawData.tds,
        turbidity: rawData.turbidity,
        temperature: rawData.temperature,
        dissolvedOxygen: rawData.dissolvedOxygen || null,
        metadata: rawData.metadata || {},
      });

      // Validate reading
      const validationErrors = reading.validate();
      if (validationErrors.length > 0) {
        throw new Error(`Validation failed: ${validationErrors.join(', ')}`);
      }

      // Save reading to database
      const savedReading = await this.sensorReadingRepo.create(reading);
      logger.info(`Sensor reading ingested: ${deviceId} at ${savedReading.timestamp}`);

      // Update device last seen
      await this.deviceRepo.updateLastSeen(deviceId);

      // Get recent readings for AI analysis
      const recentReadings = await this.sensorReadingRepo.getRecent(deviceId, config.ai.rollingWindowSize);

      // Run AI evaluation (may return null if no state change)
      const aiResult = await this.aiEngine.evaluate(savedReading, recentReadings);

      let savedEvaluation = null;
      let savedAlerts = [];

      if (aiResult) {
        // Extract evaluation and alerts from AI result
        const { evaluation, alerts: aiAlerts } = aiResult;
        
        // Save AI evaluation
        savedEvaluation = await this.aiEvaluationRepo.create(evaluation);
        logger.info(`AI evaluation generated: ${deviceId} - ${evaluation.status} (${evaluation.triggerReason})`);

        // Save alerts generated by AI engine
        if (aiAlerts && aiAlerts.length > 0) {
          for (const alert of aiAlerts) {
            const savedAlert = await this.alertRepo.create(alert);
            savedAlerts.push(savedAlert);
            logger.info(`Alert created: ${deviceId} - ${alert.severity} - ${alert.title}`);
          }
        }
      }

      return {
        reading: savedReading,
        evaluation: savedEvaluation,
        alerts: savedAlerts,
      };

    } catch (error) {
      logger.error(`Error ingesting sensor reading: ${error.message}`, error);
      throw error;
    }
  }

}
